### ISSUE TITLE
Payment gateway with method as METHOD_HTML_FORM not working with Give

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pronamic-pay-give#2]
Sorry for the incomplete information provided by me in Ticket number https://github.com/wp-pay-extensions/give/issues/1

I tried to investigate the issue further and found that Give is creating the issue for the payment gateways with the method set as METHOD_HTML_FORM. It is not creating the issue for payment gateways with the method set as METHOD_HTTP_REDIRECT.

I tested with several payment gateways having METHOD_HTTP_REDIRECT method, all of them are working fine. I found the same issue in various official Give payment gateways addons. I think this issue is at Give end and not with this library. But still, we can check if we can handle this issue at our end and fix it in this library.

I have reported this issue to Give also and provided them some videos also.

https://github.com/impress-org/givewp/issues/5538

**Comment by rvdsteege** [comment]
Gautam, I was able to reproduce the issue for gateways using the form method.

When using a HTTP redirect, it seemed to work because the payment page was using a script to break out of frames. Otherwise, the Give loading spinner would overlay the payment page.

I've resolved the issue in c05b354 by always redirecting to the built-in payment redirect page (`$payment->get_pay_redirect_url()`) and adding a script to break out of frames to that redirect page:
- https://github.com/pronamic/wp-pronamic-ideal/commit/6936ec048c6778e688386d3c15f6a6c1cbaa8eb9

**Comment by knit-pay** [comment]
hi @rvdsteege 

did this change (https://github.com/wp-pay-extensions/give/commit/c05b35475d1a3db1e07bb4b5deaf1b1589f55245) work for you? I had tried with `wp_redirect` function before raising this ticket and it was not working for me. Also, after you make the changes, I tried with `wp_safe_redirect` function also, and it's still not working for me. I am using the Firefox browser.

**Comment by rvdsteege** [comment]
It works if https://github.com/pronamic/wp-pronamic-ideal/commit/6936ec048c6778e688386d3c15f6a6c1cbaa8eb9 (break out of iframe) has been applied too, otherwise the spinner overlays the payment page and will never disappear.

**Comment by knit-pay** [comment]
Thanks, https://github.com/pronamic/wp-pronamic-ideal/commit/6936ec048c6778e688386d3c15f6a6c1cbaa8eb9 worked.
